# Site settings
title: John Hiott
email: jhiott@oolcay.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I am John Hiott! I enjoy building software.  I will make an attempt to write
  about things that I learn and interest me here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnhiott.com" # the base hostname & protocol for your site
twitter_username: johnhiott
github_username:  johnhiott

# Build settings
markdown: redcarpet
extensions: [fenced_code_blocks]
